# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ltmB7MSpB1A69h5acMSH7a3N-1Bz6jfX
"""

import streamlit as st
import joblib

model = joblib.load("svm_model_sas.pkl")
vectorizer = joblib.load("tfidf_vectorizer_sas.pkl")

label_map = {0: "Normal", 1: "Kecemasan/Depresi"}

st.title("Prediksi Kesehatan Mental dari Teks")
st.write("Masukkan teks di bawah ini dan sistem akan memprediksi apakah termasuk normal atau mengalami kecemasan/depresi.")

user_input = st.text_area("Teks masukan", height=150)

if st.button("Prediksi"):
    if user_input.strip() == "":
        st.warning("Masukkan teks terlebih dahulu.")
    else:
        vector = vectorizer.transform([user_input])
        prediction = model.predict(vector)[0]
        st.success(f"Hasil prediksi: **{label_map[prediction]}**")