# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ltmB7MSpB1A69h5acMSH7a3N-1Bz6jfX
"""

import streamlit as st
import joblib
import re
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

model = joblib.load("svm_model_sas.pkl")
vectorizer = joblib.load("tfidf_vectorizer_sas.pkl")

slang_dict = {
    "gue": "aku", "gw": "aku", "gua": "aku", "ga": "tidak", "gak": "tidak", "tak": "tidak",
    "yg": "yang", "bgt": "banget", "aja": "saja", "dah": "sudah", "tp": "tapi", "sampe": "sampai",
    "kalo": "kalau"
}

factory = StemmerFactory()
stemmer = factory.create_stemmer()

def preprocess(text):
    text = text.lower()
    text = re.sub(r"http\S+|www.\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"[^a-zA-Z\s]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    tokens = text.split()
    tokens = [slang_dict.get(token, token) for token in tokens]
    tokens = [stemmer.stem(token) for token in tokens]
    return ' '.join(tokens)

label_map = {0: "Normal", 1: "Kecemasan/Depresi"}

st.title("Prediksi Kesehatan Mental dari Teks")
st.write("Masukkan teks di bawah ini dan sistem akan memprediksi apakah termasuk normal atau mengalami kecemasan/depresi.")

user_input = st.text_area("Teks masukan", height=150)

if st.button("Prediksi"):
    if user_input.strip() == "":
        st.warning("Masukkan teks terlebih dahulu.")
    else:
        clean_input = preprocess(user_input)
        vector = vectorizer.transform([clean_input])
        prediction = model.predict(vector)[0]
        st.success(f"Hasil prediksi: **{label_map[prediction]}**")

# Menambahkan tulisan kecil
st.markdown("<p style='font-size: 12px; color: gray;'>*tidak menggantikan peran psikolog</p>", unsafe_allow_html=True)
